### ISSUE TITLE
Male Book Owners 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#85]
Male Book Owners should **not** have owner pages on the website. 

Since scholarly work has already been done on many male book owners and the focus of Books of Duchesses is on _female_ book owners male book owners should not have individual pages. 

In the owner model, all book owners are identified as "male" or "female" via a drop down box. If a book owner is identified as male, he should not have a personal page on the website. 

For example, for BL Harley MS 4431 (see here: https://booksofduchesses.com/books/BL%20Harley%20MS%204431), male owners should be listed under "Ownership Details" but users should **not** be able to click on the male owners and navigate to individual pages. Only female owners (in this case Isabel of Bavaria and Jacquetta of Luxembourg) should be live links that lead users to an individual owner page. 

Let us know if you have any questions about this or if this presents any coding problems. 
Thanks!

**Comment by fgould** [comment]
This was caused by a forgotten addition when we moved towards having the capability for multiple ownership evidences. Fixed now!

**Comment by sarahwat88** [comment]
Male book owners are still appearing as live links on the Text Pages and in the Search results. They are also appearing as live links via green book pins on the map. Can this be changed so that only women book owners appear as live links in these places? This issue seems to be fixed on the Owner Pages and the Book Pages but not in the places noted above. 

Thank you!!

**Comment by fgould** [comment]
Male owners as far as I can tell don't appear as live links in search results, but let me know if I'm wrong. All the other examples are fixed.

**Comment by sarahwat88** [comment]
Thanks for fixing these various examples! So male owners are not appearing as live links in the search result below the map but if you click on the Search tab in the upper right hand corner of the website and then scroll down to "Owners" male owners are appearing as live links there. I think this is the last place where this needs fixed. Thanks!

**Comment by fgould** [comment]
Ah, I was confused which search, but should be good now!
